name: Java 17 Maven Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        run: ./mvnw clean package spring-boot:repackage

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/jwt-auth-service-1.0.0.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: app
          path: target/

      - name: Run JAR
        run: java -jar target/jwt-auth-service-1.0.0.jar








